" Name:         MidnightBlue (v1.1)
" Description:  A colorful scheme with a dark midnightblue background
" Author:       damjan.9000@gmail.com
" Maintainer:   damjan.9000@gmail.com
" Website:      https://github.com/dam9000/colorscheme-midnightblue
" License:      Public domain (Unlicense)
" Last Updated: Sun 03 Dec 2023

" Generated by Colortemplate v2.2.3

set background=dark

hi clear
let g:colors_name = 'midnightblue'

if has('nvim')
  let s:t_Co = &t_Co
else
  let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)
endif
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#000000', '#800000', '#006400', '#808000', '#000080', '#800080', '#008080', '#c0c0c0', '#808080', '#ff0000', '#008000', '#ffff00', '#0000ff', '#ff00ff', '#00ffff', '#eeeeee']
  " Nvim uses g:terminal_color_{0-15} instead
  if has('nvim')
    for i in range(g:terminal_ansi_colors->len())
      let g:terminal_color_{i} = g:terminal_ansi_colors[i]
    endfor
  endif
endif
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link CurSearch IncSearch
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign CursorLineNr
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link MessageWindow WarningMsg
hi! link Number Constant
hi! link Operator Statement
hi! link PmenuKind Pmenu
hi! link PmenuKindSel PmenuSel
hi! link PmenuExtra Pmenu
hi! link PmenuExtraSel PmenuSel
hi! link PopupNotification WarningMsg
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor
hi! link CursorIM Cursor
if get(g:, 'midnightblue_transp_bg', 0) && !has('gui_running')
  hi Normal guifg=#eeeeee guibg=NONE gui=NONE cterm=NONE
  hi Terminal guifg=#eeeeee guibg=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#0000ff guibg=NONE gui=NONE cterm=NONE
else
  hi Normal guifg=#eeeeee guibg=#081035 gui=NONE cterm=NONE
  hi Terminal guifg=#eeeeee guibg=#081035 gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#0000ff guibg=#081035 gui=NONE cterm=NONE
endif
hi ColorColumn guifg=NONE guibg=#080a2a gui=NONE cterm=NONE
hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi Cursor guifg=#000000 guibg=#ffff00 gui=NONE cterm=NONE
hi! link CursorColumn CursorLine
hi CursorLine guifg=NONE guibg=#101838 gui=NONE cterm=NONE
hi CursorLineNr guifg=#c0c0c0 guibg=#182040 gui=NONE cterm=NONE
hi LineNr guifg=#384060 guibg=#101838 gui=NONE cterm=NONE
hi SignColumn guifg=#384060 guibg=#101838 gui=NONE cterm=NONE
hi DiffAdd guifg=#eeeeee guibg=#104020 gui=NONE cterm=NONE
hi DiffChange guifg=#eeeeee guibg=#204070 gui=NONE cterm=NONE
hi DiffDelete guifg=#eeeeee guibg=#601020 gui=NONE cterm=NONE
hi DiffText guifg=#eeeeee guibg=#081035 gui=bold,reverse cterm=bold,reverse
hi Directory guifg=#eeeeee guibg=NONE gui=NONE cterm=NONE
hi ErrorMsg guifg=#eeeeee guibg=#800000 gui=NONE cterm=NONE
hi FoldColumn guifg=#eeeeee guibg=#081035 gui=NONE cterm=NONE
hi Folded guifg=#eeeeee guibg=#081035 gui=italic cterm=italic
hi IncSearch guifg=#000000 guibg=#00bfff gui=NONE cterm=NONE
hi MatchParen guifg=NONE guibg=NONE guisp=#ffff00 gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
hi ModeMsg guifg=#eeeeee guibg=#081035 gui=NONE cterm=NONE
hi MoreMsg guifg=#ffa500 guibg=#081035 gui=NONE cterm=NONE
hi NonText guifg=#8a8a8a guibg=NONE gui=NONE cterm=NONE
hi Pmenu guifg=#eeeeee guibg=#0000ff gui=NONE cterm=NONE
hi PmenuSel guifg=#eeeeee guibg=#000000 gui=reverse cterm=reverse
hi PmenuSbar guifg=#000000 guibg=#808080 gui=NONE cterm=NONE
hi PmenuThumb guifg=#eeeeee guibg=#c0c0c0 gui=NONE cterm=NONE
hi Question guifg=#ffa500 guibg=#081035 gui=NONE cterm=NONE
hi Search guifg=#eeeeee guibg=#0000ff gui=NONE cterm=NONE
hi SpecialKey guifg=#eeeeee guibg=#081035 gui=NONE cterm=NONE
hi SpellBad guifg=NONE guibg=NONE guisp=#ff0000 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellCap guifg=NONE guibg=NONE guisp=#ff00ff gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellLocal guifg=NONE guibg=NONE guisp=#ffff00 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellRare guifg=NONE guibg=NONE guisp=#00ffff gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi StatusLine guifg=#eeeeee guibg=#384060 gui=NONE cterm=NONE
hi StatusLineNC guifg=#384060 guibg=#182040 gui=NONE cterm=NONE
hi TabLineFill guifg=#000000 guibg=#525252 gui=NONE cterm=NONE
hi TabLine guifg=#000000 guibg=#616161 gui=NONE cterm=NONE
hi TabLineSel guifg=#000000 guibg=#808080 gui=NONE cterm=NONE
hi Title guifg=#00bfff guibg=NONE gui=NONE cterm=NONE
hi VertSplit guifg=#c0c0c0 guibg=#101838 gui=NONE cterm=NONE
hi Visual guifg=NONE guibg=#384060 gui=NONE cterm=NONE
hi VisualNOS guifg=NONE guibg=#283050 gui=NONE cterm=NONE
hi WarningMsg guifg=#ee82ee guibg=#081035 gui=NONE cterm=NONE
hi WildMenu guifg=#eeeeee guibg=#081035 gui=NONE cterm=NONE
hi Whitespace guifg=#800000 guibg=NONE gui=NONE cterm=NONE
hi Comment guifg=#8a8a8a guibg=NONE gui=italic cterm=italic
hi Constant guifg=#9f79ee guibg=NONE gui=NONE cterm=NONE
hi Error guifg=#eeeeee guibg=#ff0000 gui=bold cterm=bold
hi Function guifg=#1e90ff guibg=NONE gui=NONE cterm=NONE
hi Identifier guifg=#eeeeee guibg=NONE gui=NONE cterm=NONE
hi Ignore guifg=#eeeeee guibg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#ee82ee guibg=NONE gui=NONE cterm=NONE
hi Special guifg=#ffa500 guibg=NONE gui=NONE cterm=NONE
hi Statement guifg=#ffff64 guibg=NONE gui=NONE cterm=NONE
hi Property guifg=#8ee5ee guibg=NONE gui=NONE cterm=NONE
hi String guifg=#66cdaa guibg=NONE gui=NONE cterm=NONE
hi Todo guifg=#000000 guibg=#00ffff gui=NONE cterm=NONE
hi Type guifg=#32cd32 guibg=NONE gui=NONE cterm=NONE
hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
hi ToolbarLine guifg=NONE guibg=#384060 gui=NONE cterm=NONE
hi ToolbarButton guifg=#000000 guibg=#00bfff gui=bold cterm=bold
hi! link makeIdent Property
hi NormalFloat guifg=#eeeeee guibg=#081040 gui=NONE cterm=NONE
hi FloatTitle guifg=#00bfff guibg=#000000 gui=NONE cterm=NONE
hi FloatBorder guifg=#00bfff guibg=#081035 gui=NONE cterm=NONE
if !s:italics
  hi Folded gui=NONE cterm=NONE
  hi Comment gui=NONE cterm=NONE
endif
if has("nvim")
  hi @punctuation guifg=#eeeeee guibg=NONE gui=NONE cterm=NONE
  hi! link @property Property
  hi! link @field Property
  hi! link @lsp.type.property Property
  hi! link @type.qualifier Keyword
  hi! link @variable.builtin Special
  hi! link @punctuation.special Special
  hi! link @lsp.typemod.variable.defaultLibrary Special
endif
hi IblIndent guifg=#182040 guibg=NONE gui=NONE cterm=NONE
hi IblScope guifg=#283050 guibg=NONE gui=NONE cterm=NONE
hi GitGutterAdd guifg=#32cd32 guibg=#101838 gui=NONE cterm=NONE
hi GitGutterChange guifg=#87ceeb guibg=#101838 gui=NONE cterm=NONE
hi GitGutterDelete guifg=#ff0000 guibg=#101838 gui=NONE cterm=NONE
hi GitSignsAdd guifg=#32cd32 guibg=#101838 gui=NONE cterm=NONE
hi GitSignsChange guifg=#87ceeb guibg=#101838 gui=NONE cterm=NONE
hi GitSignsDelete guifg=#ff0000 guibg=#101838 gui=NONE cterm=NONE
hi NeoTreeCursorLine guifg=NONE guibg=#182040 gui=NONE cterm=NONE
hi NeoTreeGitAdded guifg=#32cd32 guibg=NONE gui=NONE cterm=NONE
hi NeoTreeGitModified guifg=#87ceeb guibg=NONE gui=NONE cterm=NONE
hi NeoTreeGitDeleted guifg=#ff0000 guibg=NONE gui=NONE cterm=NONE
hi TelescopeNormal guifg=#eeeeee guibg=#081040 gui=NONE cterm=NONE
hi TelescopeResultsDiffAdd guifg=#32cd32 guibg=NONE gui=NONE cterm=NONE
hi TelescopeResultsDiffChange guifg=#87ceeb guibg=NONE gui=NONE cterm=NONE
hi TelescopeResultsDiffDelete guifg=#ff0000 guibg=NONE gui=NONE cterm=NONE

if s:t_Co >= 256
  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Conditional Statement
  hi! link CurSearch IncSearch
  hi! link CursorLineFold FoldColumn
  hi! link CursorLineSign CursorLineNr
  hi! link Debug Special
  hi! link Define PreProc
  hi! link Delimiter Special
  hi! link Exception Statement
  hi! link Float Constant
  hi! link Include PreProc
  hi! link Keyword Statement
  hi! link Label Statement
  hi! link Macro PreProc
  hi! link MessageWindow WarningMsg
  hi! link Number Constant
  hi! link Operator Statement
  hi! link PmenuKind Pmenu
  hi! link PmenuKindSel PmenuSel
  hi! link PmenuExtra Pmenu
  hi! link PmenuExtraSel PmenuSel
  hi! link PopupNotification WarningMsg
  hi! link PopupSelected PmenuSel
  hi! link PreCondit PreProc
  hi! link QuickFixLine Search
  hi! link Repeat Statement
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link StorageClass Type
  hi! link Structure Type
  hi! link Tag Special
  hi! link Typedef Type
  hi! link lCursor Cursor
  hi! link CursorIM Cursor
  if get(g:, 'midnightblue_transp_bg', 0)
    hi Normal ctermfg=255 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=255 ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=21 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=255 ctermbg=234 cterm=NONE
    hi Terminal ctermfg=255 ctermbg=234 cterm=NONE
    hi EndOfBuffer ctermfg=21 ctermbg=234 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=233 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=16 ctermbg=226 cterm=NONE
  hi! link CursorColumn CursorLine
  hi CursorLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorLineNr ctermfg=250 ctermbg=236 cterm=NONE
  hi LineNr ctermfg=60 ctermbg=235 cterm=NONE
  hi SignColumn ctermfg=60 ctermbg=235 cterm=NONE
  hi DiffAdd ctermfg=255 ctermbg=22 cterm=NONE
  hi DiffChange ctermfg=255 ctermbg=25 cterm=NONE
  hi DiffDelete ctermfg=255 ctermbg=52 cterm=NONE
  hi DiffText ctermfg=255 ctermbg=234 cterm=bold,reverse
  hi Directory ctermfg=255 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=255 ctermbg=88 cterm=NONE
  hi FoldColumn ctermfg=255 ctermbg=234 cterm=NONE
  hi Folded ctermfg=255 ctermbg=234 cterm=italic
  hi IncSearch ctermfg=16 ctermbg=39 cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=underline
  hi ModeMsg ctermfg=255 ctermbg=234 cterm=NONE
  hi MoreMsg ctermfg=214 ctermbg=234 cterm=NONE
  hi NonText ctermfg=245 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=255 ctermbg=21 cterm=NONE
  hi PmenuSel ctermfg=255 ctermbg=16 cterm=reverse
  hi PmenuSbar ctermfg=16 ctermbg=244 cterm=NONE
  hi PmenuThumb ctermfg=255 ctermbg=250 cterm=NONE
  hi Question ctermfg=214 ctermbg=234 cterm=NONE
  hi Search ctermfg=255 ctermbg=21 cterm=NONE
  hi SpecialKey ctermfg=255 ctermbg=234 cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine ctermfg=255 ctermbg=60 cterm=NONE
  hi StatusLineNC ctermfg=60 ctermbg=236 cterm=NONE
  hi TabLineFill ctermfg=16 ctermbg=239 cterm=NONE
  hi TabLine ctermfg=16 ctermbg=241 cterm=NONE
  hi TabLineSel ctermfg=16 ctermbg=244 cterm=NONE
  hi Title ctermfg=39 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=250 ctermbg=235 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=60 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=237 cterm=NONE
  hi WarningMsg ctermfg=213 ctermbg=234 cterm=NONE
  hi WildMenu ctermfg=255 ctermbg=234 cterm=NONE
  hi Whitespace ctermfg=88 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=245 ctermbg=NONE cterm=italic
  hi Constant ctermfg=141 ctermbg=NONE cterm=NONE
  hi Error ctermfg=255 ctermbg=196 cterm=bold
  hi Function ctermfg=33 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=255 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=255 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=213 ctermbg=NONE cterm=NONE
  hi Special ctermfg=214 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=227 ctermbg=NONE cterm=NONE
  hi Property ctermfg=116 ctermbg=NONE cterm=NONE
  hi String ctermfg=79 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=16 ctermbg=51 cterm=NONE
  hi Type ctermfg=40 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi ToolbarLine ctermfg=NONE ctermbg=60 cterm=NONE
  hi ToolbarButton ctermfg=16 ctermbg=39 cterm=bold
  hi! link makeIdent Property
  hi NormalFloat ctermfg=255 ctermbg=17 cterm=NONE
  hi FloatTitle ctermfg=39 ctermbg=16 cterm=NONE
  hi FloatBorder ctermfg=39 ctermbg=234 cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  if has("nvim")
    hi @punctuation ctermfg=255 ctermbg=NONE cterm=NONE
    hi! link @property Property
    hi! link @field Property
    hi! link @lsp.type.property Property
    hi! link @type.qualifier Keyword
    hi! link @variable.builtin Special
    hi! link @punctuation.special Special
    hi! link @lsp.typemod.variable.defaultLibrary Special
  endif
  hi IblIndent ctermfg=236 ctermbg=NONE cterm=NONE
  hi IblScope ctermfg=237 ctermbg=NONE cterm=NONE
  hi GitGutterAdd ctermfg=40 ctermbg=235 cterm=NONE
  hi GitGutterChange ctermfg=117 ctermbg=235 cterm=NONE
  hi GitGutterDelete ctermfg=196 ctermbg=235 cterm=NONE
  hi GitSignsAdd ctermfg=40 ctermbg=235 cterm=NONE
  hi GitSignsChange ctermfg=117 ctermbg=235 cterm=NONE
  hi GitSignsDelete ctermfg=196 ctermbg=235 cterm=NONE
  hi NeoTreeCursorLine ctermfg=NONE ctermbg=236 cterm=NONE
  hi NeoTreeGitAdded ctermfg=40 ctermbg=NONE cterm=NONE
  hi NeoTreeGitModified ctermfg=117 ctermbg=NONE cterm=NONE
  hi NeoTreeGitDeleted ctermfg=196 ctermbg=NONE cterm=NONE
  hi TelescopeNormal ctermfg=255 ctermbg=17 cterm=NONE
  hi TelescopeResultsDiffAdd ctermfg=40 ctermbg=NONE cterm=NONE
  hi TelescopeResultsDiffChange ctermfg=117 ctermbg=NONE cterm=NONE
  hi TelescopeResultsDiffDelete ctermfg=196 ctermbg=NONE cterm=NONE
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'midnightblue_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=Blue ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
    hi EndOfBuffer ctermfg=Blue ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=Black cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=Black ctermbg=Yellow cterm=NONE
  hi! link CursorColumn CursorLine
  hi CursorLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CursorLineNr ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi LineNr ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi SignColumn ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi DiffAdd ctermfg=White ctermbg=DarkGreen cterm=NONE
  hi DiffChange ctermfg=White ctermbg=DarkCyan cterm=NONE
  hi DiffDelete ctermfg=White ctermbg=DarkRed cterm=NONE
  hi DiffText ctermfg=White ctermbg=Black cterm=bold,reverse
  hi Directory ctermfg=White ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=White ctermbg=DarkRed cterm=NONE
  hi FoldColumn ctermfg=White ctermbg=Black cterm=NONE
  hi Folded ctermfg=White ctermbg=Black cterm=italic
  hi IncSearch ctermfg=Black ctermbg=LightBlue cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=underline
  hi ModeMsg ctermfg=White ctermbg=Black cterm=NONE
  hi MoreMsg ctermfg=DarkYellow ctermbg=Black cterm=NONE
  hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=White ctermbg=Blue cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=Black cterm=reverse
  hi PmenuSbar ctermfg=Black ctermbg=Grey cterm=NONE
  hi PmenuThumb ctermfg=White ctermbg=LightGrey cterm=NONE
  hi Question ctermfg=DarkYellow ctermbg=Black cterm=NONE
  hi Search ctermfg=White ctermbg=Blue cterm=NONE
  hi SpecialKey ctermfg=White ctermbg=Black cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine ctermfg=White ctermbg=LightGrey cterm=NONE
  hi StatusLineNC ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi TabLineFill ctermfg=Black ctermbg=Grey cterm=NONE
  hi TabLine ctermfg=Black ctermbg=Grey cterm=NONE
  hi TabLineSel ctermfg=Black ctermbg=Grey cterm=NONE
  hi Title ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi Visual ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi WarningMsg ctermfg=LightMagenta ctermbg=Black cterm=NONE
  hi WildMenu ctermfg=White ctermbg=Black cterm=NONE
  hi Whitespace ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Grey ctermbg=NONE cterm=italic
  hi Constant ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Error ctermfg=White ctermbg=Red cterm=bold
  hi Function ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=White ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=White ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=LightMagenta ctermbg=NONE cterm=NONE
  hi Special ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Statement ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Property ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi String ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Black ctermbg=Cyan cterm=NONE
  hi Type ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi ToolbarLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi ToolbarButton ctermfg=Black ctermbg=LightBlue cterm=bold
  hi! link makeIdent Property
  hi NormalFloat ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi FloatTitle ctermfg=LightBlue ctermbg=Black cterm=NONE
  hi FloatBorder ctermfg=LightBlue ctermbg=Black cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  if has("nvim")
    hi @punctuation ctermfg=White ctermbg=NONE cterm=NONE
    hi! link @property Property
    hi! link @field Property
    hi! link @lsp.type.property Property
    hi! link @type.qualifier Keyword
    hi! link @variable.builtin Special
    hi! link @punctuation.special Special
    hi! link @lsp.typemod.variable.defaultLibrary Special
  endif
  hi IblIndent ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi IblScope ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi GitGutterAdd ctermfg=LightGreen ctermbg=DarkGrey cterm=NONE
  hi GitGutterChange ctermfg=LightBlue ctermbg=DarkGrey cterm=NONE
  hi GitGutterDelete ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi GitSignsAdd ctermfg=LightGreen ctermbg=DarkGrey cterm=NONE
  hi GitSignsChange ctermfg=LightBlue ctermbg=DarkGrey cterm=NONE
  hi GitSignsDelete ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi NeoTreeCursorLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi NeoTreeGitAdded ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi NeoTreeGitModified ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi NeoTreeGitDeleted ctermfg=Red ctermbg=NONE cterm=NONE
  hi TelescopeNormal ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi TelescopeResultsDiffAdd ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi TelescopeResultsDiffChange ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi TelescopeResultsDiffDelete ctermfg=Red ctermbg=NONE cterm=NONE
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 0
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi PopupSelected term=reverse
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color:  bg_main         #081035               234       Black        ; Normal:bg
" Color:  bg0             #080a2a               233       Black        ; ColorColumn
" Color:  bg1             #081040               ~         DarkBlue     ; NormalFloat
" Color:  bg2             #101838               235       DarkGrey     ; SignColumn:bg LineNr:bg CursorLine:bg
" Color:  bg3             #182040               236       DarkGrey     ; CursorLineNr:bg StatusLineNC:bg
" Color:  bg4             #283050               237       DarkGrey     ;
" Color:  bg5             #384060               ~         LightGrey    ; SignColumn:fg LineNr:fg StatusLine:bg Visual
" Color:  black           #000000               ~         Black
" Color:  darkred         #800000               ~         DarkRed
" Color:  darkgreen       #006400               ~         DarkGreen
" Color:  darkyellow      #808000               ~         DarkYellow
" Color:  darkblue        #000080               ~         DarkBlue
" Color:  purple          #800080               ~         DarkMagenta
" Color:  darkcyan        #008080               ~         DarkCyan
" Color:  silver          #c0c0c0               ~         LightGrey
" Color:  grey            #808080               ~         Grey
" Color:  red             #ff0000               ~         Red
" Color:  green           #008000               ~         Green
" Color:  yellow          #ffff00               ~         Yellow
" Color:  blue            #0000ff               ~         Blue
" Color:  magenta         #ff00ff               ~         Magenta
" Color:  cyan            #00ffff               ~         Cyan
" Color:  white           #eeeeee               ~         White
" Color:  brightwhite     #ffffff               ~         White
" Color:  brightyellow    #ffff64               ~         LightYellow
" Color:  grey25          #404040               ~         Grey
" Color:  grey32          #525252               ~         Grey
" Color:  grey38          #616161               ~         Grey
" Color:  grey44          #707070               ~         Grey
" Color:  grey54          #8A8A8A               245       Grey  ; Comment
" Color:  deepskyblue     #00BFFF               39        LightBlue    ; Title FloatTitle IncSearch
" Color:  dodgerblue      #1E90FF               ~         LightBlue    ; Function
" Color:  mediumpurple2   #9F79EE               ~         DarkMagenta  ; Constant
" Color:  violet          #EE82EE               ~         LightMagenta ; PreProc
" Color:  lightpink2      #EEA2AD               ~         LightMagenta ; mode:replace
" Color:  orange          #FFA500               ~         DarkYellow   ; Special
" Color:  burlywood       #DEB887               ~         DarkYellow   ; mode:command
" Color:  limegreen       #32CD32               ~         LightGreen   ; Type, GitSignsAdd
" Color:  aquamarine3     #66CDAA               ~         DarkCyan     ; String
" Color:  cadetblue2      #8EE5EE               ~         LightCyan    ; Property
" Color:  skyblue         #87CEEB               ~         LightBlue
" Color:  diffadd         #104020               ~         DarkGreen
" Color:  diffchange      #204070               ~         DarkCyan
" Color:  diffdelete      #601020               ~         DarkRed
" Term colors: black darkred darkgreen darkyellow darkblue purple  darkcyan silver
" Term colors: grey  red     green     yellow     blue     magenta cyan     white
" vim: et ts=8 sw=2 sts=2
